<<<<<<< HEAD
[tool.poetry]
name = "animal_classificator"
version = "0.1.0"
description = ""
authors = ["Victoria Lebedeva"]

[tool.poetry.dependencies]
python = ">=3.7, <3.11"
Flask = "^2.1.2"
Pillow = "^9.1.1"
tensorflow = "^2.9.1"


[tool.poetry.dev-dependencies]
black = {version = "^22.3.0", allow-prereleases = true}

[tool.poetry.scripts]
app="animal_classificator.app:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
=======
[tool.poetry]
name = "animal_classificator"
version = "0.1.0"
description = ""
authors = ["Victoria Lebedeva"]

[tool.poetry.dependencies]
python = ">=3.7, <3.11"
Flask = "^2.1.2"
Pillow = "^9.1.1"
tensorflow = "^2.9.1"


[tool.poetry.dev-dependencies]
black = {version = "^22.3.0", allow-prereleases = true}

[tool.poetry.scripts]
app="animal_classificator.app:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
>>>>>>> c7c4a211ca9139b1f540f869dcae4643943ed7a9
